import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openFeishuCapture } from '../src/feishu-capture.js';

const scope = { accountId:'default', entryAgentId:'xiaojie', allowedSenderIds:['ou_test'], allowedConversationIds:['oc_test'], enabledModules:['okr'] };
test('未知写入回执给出核对步骤，续接只核对已保存投影不重跑模型',async t=>{
  const {standaloneFixture}=await import('../examples/okr-standalone-fixture.js');
  const dir=mkdtempSync(join(tmpdir(),'okr-write-unknown-'));let uncertain=false;
  const f=standaloneFixture(dir,{bridgeFailure:r=>{if(uncertain&&r.command==='replace')throw new Error('WRITE_RESULT_UNKNOWN');}});
  t.after(async()=>{await f.close();rmSync(dir,{recursive:true,force:true});});
  await f.send('om_open','小婕 okr 讨论');const parent=f.sent.at(-1).message_id;
  uncertain=true;const failure=await f.send('om_answer','合成背景回答',{parent});
  assert.equal(failure.code,'WRITE_RESULT_UNKNOWN');assert.match(failure.receipt,/正文.*核对/);assert.match(failure.receipt,/小婕 okr 续接/);assert.match(failure.receipt,/不要.*重试分析/);
  const calls=f.guideCalls;uncertain=false;
  const resumed=await f.send('om_resume','小婕 okr 续接');assert.equal(resumed.status,'okr_open');assert.equal(f.guideCalls,calls);
});
test('编辑窗口不可用说明原因和恢复，重置分析仅纠正命令而不读写或调用模型',async t=>{
  const {standaloneFixture}=await import('../examples/okr-standalone-fixture.js');
  const dir=mkdtempSync(join(tmpdir(),'okr-editor-error-'));let unavailable=false;
  const f=standaloneFixture(dir,{bridgeFailure:r=>{if(unavailable&&r.command==='read')throw new Error('EDITOR_UNAVAILABLE');}});
  t.after(async()=>{await f.close();rmSync(dir,{recursive:true,force:true});});
  await f.send('om_open','小婕 okr 讨论');const parent=f.sent.at(-1).message_id;
  unavailable=true;
  const error=await f.send('om_read_error','合成回答',{parent});
  assert.equal(error.code,'EDITOR_UNAVAILABLE');assert.match(error.receipt,/编辑窗口/);assert.match(error.receipt,/打开备忘录/);assert.match(error.receipt,/续接/);
  const operations=f.operations.length,calls=f.guideCalls;
  const hint=await f.send('om_typo','重置分析',{parent});
  assert.equal(hint.status,'okr_retry_help');assert.match(hint.receipt,/重试分析/);
  assert.equal(f.operations.length,operations);assert.equal(f.guideCalls,calls);
});
test('失败回执说明超时和保存状态，关联重试复用原回答且重投重启不重调',async t=>{
  const {standaloneFixture}=await import('../examples/okr-standalone-fixture.js');
  const dir=mkdtempSync(join(tmpdir(),'okr-retry-'));let seen=[];
  const f=standaloneFixture(dir,{guide:async input=>{seen.push(input.answer);if(seen.length===1)throw new Error('MODEL_TIMEOUT');return {stage:'direction',summary:'合成背景已收到',advice:'先讨论一个目标',questions:['合成目标的意义是什么？'],draft:null};}});
  t.after(async()=>{await f.close();rmSync(dir,{recursive:true,force:true});});
  await f.send('om_open','小婕 okr 讨论');
  const original='合成回答：作为独立目标讨论';
  const failure=await f.send('om_fail',original,{parent:f.sent.at(-1).message_id});
  assert.equal(failure.status,'okr_guidance_failed');assert.match(failure.receipt,/超时/);
  assert.match(failure.receipt,/草案.*未更新|未更新.*草案/);assert.match(failure.receipt,/重试分析/);
  assert.ok(f.notes.some(n=>n.plaintext.includes(original)));
  const failedParent=f.sent.at(-1).message_id;
  await f.restart();
  const retried=await f.send('om_retry','重试分析',{parent:failedParent});
  assert.equal(retried.status,'okr_guided');assert.deepEqual(seen,[original,original]);
  await f.restart();assert.equal((await f.send('om_retry','重试分析',{parent:failedParent})).status,'okr_guided');assert.equal(seen.length,2);
  assert.equal((await f.send('om_invalid_retry','重试分析',{parent:f.sent.at(-1).message_id})).status,'okr_retry_unavailable');
  assert.equal((await f.send('om_bare_retry','小婕 okr 重试分析')).status,'okr_retry_unavailable');
  assert.equal(seen.length,2);
});
test('同身份关联OKR的短否定是业务回答，入口否定查询仍拒绝且重复回答不重调模型',async t=>{
  const {standaloneFixture}=await import('../examples/okr-standalone-fixture.js');
  const dir=mkdtempSync(join(tmpdir(),'okr-short-answer-')),f=standaloneFixture(dir);
  t.after(async()=>{await f.close();rmSync(dir,{recursive:true,force:true});});
  await f.send('om_open','小婕 okr 讨论');
  const parent=f.sent.at(-1).message_id;
  const result=await f.send('om_no','不需要',{parent});
  assert.equal(result.status,'okr_guided');assert.equal(f.guideCalls,1);
  assert.ok(f.notes.some(x=>x.plaintext.includes('不需要')));
  assert.equal((await f.send('om_no','不需要',{parent})).status,'okr_guided');
  assert.equal(f.guideCalls,1);
  const writes=f.operations.filter(x=>['create','append','replace'].includes(x.command)).length;
  assert.equal((await f.send('om_unlinked','不需要')).status,'not_handled');
  assert.equal((await f.send('om_negated','小婕 okr 不要查询当前目标')).status,'okr_help');
  assert.equal((await f.send('om_link_negated','不要查询当前目标',{parent})).status,'okr_help');
  assert.equal(f.guideCalls,1);
  assert.equal(f.operations.filter(x=>['create','append','replace'].includes(x.command)).length,writes);
});
test('只配置OKR可启动，不建立GTD日志，禁用GTD请求明确拒绝', async t => {
  const dir=mkdtempSync(join(tmpdir(),'okr-only-'));
  let capture;
  t.after(async()=>{await capture?.close();rmSync(dir,{recursive:true,force:true});});
  const text='小婕 gtd 收集：不应创建';
  const feishu={getMessage:async()=>({message_id:'om_1',chat_id:'oc_test',sender:{id:'ou_test',id_type:'open_id',sender_type:'user'},msg_type:'text',create_time:'1790474400000',body:{content:JSON.stringify({text})}}),reply:async()=>({message_id:'om_bot',chat_id:'oc_test'})};
  capture=openFeishuCapture({stateDir:dir,config:scope,feishu});
  const result=await capture.handle({Provider:'feishu',AccountId:'default',AgentId:'xiaojie',SenderId:'ou_test',NativeChannelId:'oc_test',MessageSid:'om_1',rawText:text});
  assert.equal(result.status,'module_disabled');
  assert.equal(existsSync(join(dir,'capture.sqlite')),false);
  assert.deepEqual(await capture.recover(),[]);
});

test('OpenClaw仅启用OKR无需提醒helper、sourceId或listId', async t => {
  const { writeFileSync } = await import('node:fs');
  const { openRuntime } = await import('../openclaw/runtime.js');
  const dir=mkdtempSync(join(tmpdir(),'okr-runtime-'));
  let runtime;
  t.after(async()=>{await runtime?.close();rmSync(dir,{recursive:true,force:true});});
  const path=join(dir,'config.json');
  writeFileSync(path,JSON.stringify({enabledModules:['okr'],usagePath:join(dir,'usage.sqlite'),model:{maxBudgetUsd:1,maxCalls:10},okr:{account:'synthetic',folder:'Notes',journalDir:join(dir,'journal')}}));
  runtime=await openRuntime({config:{...scope,runtimeConfigPath:path,stateDir:join(dir,'state')},hostConfig:{channels:{feishu:{appId:'synthetic',appSecret:'synthetic'}}},googleKey:()=>async()=> 'synthetic'});
  assert.deepEqual(await runtime.recover(),[]);
  assert.equal(existsSync(join(dir,'state','adapter.sqlite')),false);
});

test('OKR单模块七轮讨论、暂停重启、原身份草案确认和旧入口读回同一最新稿', async t => {
  const { standaloneFixture }=await import('../examples/okr-standalone-fixture.js');
  const dir=mkdtempSync(join(tmpdir(),'okr-flow-')),f=standaloneFixture(dir);
  t.after(async()=>{await f.close();rmSync(dir,{recursive:true,force:true});});
  assert.equal((await f.send('om_open','小婕 okr 讨论')).status,'okr_open');
  await f.send('om_r1','合成回答1',{parent:f.sent.at(-1).message_id});
  assert.equal((await f.send('om_pause','暂停',{parent:f.sent.at(-1).message_id})).status,'okr_paused');
  await f.restart();
  assert.equal((await f.send('om_resume','小婕 gtd okr 续接')).status,'okr_open');
  let ready;
  for(let i=2;i<=7;i++) ready=await f.send('om_r'+i,'合成回答'+i,{parent:f.sent.at(-1).message_id});
  const parent=f.sent.at(-1).message_id;
  assert.ok(ready.draftVersion);
  assert.equal(f.notes.length,1);
  assert.equal((await f.send('om_wrong','小婕 okr 确认定稿',{parent,sender:'ou_other'})).status,'okr_paused');
  assert.equal((await f.send('om_unlinked','小婕 okr 确认定稿')).status,'okr_needs_confirmation');
  await f.restart();
  const result=await f.send('om_confirm','确认定稿',{parent});
  assert.equal(result.status,'okr_finalized');
  const calls=f.guideCalls,writes=f.operations.filter(c=>['create','append','replace'].includes(c)).length;
  await f.restart();
  assert.equal((await f.send('om_confirm','确认定稿',{parent})).noteId,result.noteId);
  assert.equal(f.guideCalls,calls);
  assert.equal(f.operations.filter(c=>['create','append','replace'].includes(c)).length,writes);
  assert.equal(f.notes.length,2);
  assert.match((await f.send('om_read','小婕 gtd okr 讨论')).receipt,/当前目标|最新/);
  assert.ok(f.notes.find(n=>n.id===result.noteId).nativeTags.includes('#KR3'));
});
test('原生标签写入失败说明正文和格式核对步骤，不诱导重新分析',async t=>{
  const {standaloneFixture}=await import('../examples/okr-standalone-fixture.js');
  const dir=mkdtempSync(join(tmpdir(),'okr-tag-receipt-'));let fail=false;
  const f=standaloneFixture(dir,{bridgeFailure:r=>{if(fail&&r.command==='replace')throw new Error('TAG_WRITE_FAILED');}});
  t.after(async()=>{await f.close();rmSync(dir,{recursive:true,force:true});});
  await f.send('om_open','小婕 okr 讨论');const parent=f.sent.at(-1).message_id;
  fail=true;const r=await f.send('om_answer','合成回答',{parent});assert.equal(r.code,'TAG_WRITE_FAILED');assert.match(r.receipt,/原生标签/);assert.match(r.receipt,/小婕 okr 续接/);assert.match(r.receipt,/不要.*重试分析/);
});
